# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SIhNelWuiNAJv8R2nEbUQxohUJlDfuf
"""

int main(void)
{
    HAL_Init();

    SystemClock_Config();

    MX_GPIO_Init();
    MX_DMA_Init();
    MX_ADC1_Init();

    /* Inicialización del TDA potenciómetro */
    pote_init();

    while (1)
    {
        /* Resto de la aplicación */
    }
}