# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SIhNelWuiNAJv8R2nEbUQxohUJlDfuf
"""

#include "potenciometro.h"
#include <stdlib.h>

/*
 * Variables generadas por CubeMX.
 * Se encuentran definidas en main.c.
 */
extern ADC_HandleTypeDef hadc1;

/*
 * Buffer utilizado por el DMA del ADC.
 *
 * adc_buffer[0] -> Potenciómetro R
 * adc_buffer[1] -> Potenciómetro G
 * adc_buffer[2] -> Potenciómetro B
 */
extern uint16_t adc_buffer[3];


/*
 * Inicialización del ADC mediante DMA.
 */
void pote_init(void)
{
    HAL_ADC_Start_DMA(&hadc1,
                      (uint32_t *)adc_buffer,
                      3);
}


/*
 * Conversión ADC de 12 bits a posición de matriz 32x32.
 *
 * ADC: 0 ... 4095
 * Salida: 0 ... 31
 */
uint8_t adc_a_posicion(uint16_t valor_raw)
{
    return (uint8_t)((valor_raw * 32U) / 4096U);
}


/*
 * Conversión ADC de 12 bits a brillo de 8 bits.
 *
 * ADC: 0 ... 4095
 * Salida: 0 ... 255
 */
uint8_t adc_a_brillo(uint16_t valor_raw)
{
    return (uint8_t)(valor_raw >> 4);
}


/*
 * Filtro para evitar pequeñas variaciones
 * producidas por ruido en la lectura del ADC.
 */
static uint8_t aplicar_filtro_ruido(uint8_t nuevo,
                                    uint8_t anterior)
{
    if (abs((int)nuevo - (int)anterior) <= 2)
    {
        return anterior;
    }

    return nuevo;
}


/*
 * Lee los tres potenciómetros y devuelve sus valores
 * mediante punteros.
 *
 * r -> valor procesado del potenciómetro R
 * g -> valor procesado del potenciómetro G
 * b -> valor procesado del potenciómetro B
 */
void leer_potenciometros(uint8_t *r,
                         uint8_t *g,
                         uint8_t *b)
{
    uint8_t r_nuevo;
    uint8_t g_nuevo;
    uint8_t b_nuevo;

    static uint8_t r_anterior = 0;
    static uint8_t g_anterior = 0;
    static uint8_t b_anterior = 0;

    /*
     * Obtener los valores actuales del DMA.
     */
    r_nuevo = adc_a_posicion(adc_buffer[0]);
    g_nuevo = adc_a_posicion(adc_buffer[1]);
    b_nuevo = adc_a_brillo(adc_buffer[2]);

    /*
     * Aplicar filtro de ruido.
     */
    r_anterior = aplicar_filtro_ruido(r_nuevo, r_anterior);
    g_anterior = aplicar_filtro_ruido(g_nuevo, g_anterior);
    b_anterior = aplicar_filtro_ruido(b_nuevo, b_anterior);

    /*
     * Devolver los valores al módulo que realizó la llamada.
     */
    *r = r_anterior;
    *g = g_anterior;
    *b = b_anterior;
}