# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SIhNelWuiNAJv8R2nEbUQxohUJlDfuf
"""

#ifndef POTENCIOMETRO_H
#define POTENCIOMETRO_H

#include "main.h"
#include <stdint.h>

/* Inicializa el ADC y el DMA */
void pote_init(void);

/* Lee los tres potenciómetros y devuelve sus valores RGB */
void leer_potenciometros(uint8_t *r,
                         uint8_t *g,
                         uint8_t *b);

/* Convierte un valor ADC de 12 bits a un valor de 0 a 31 */
uint8_t adc_a_posicion(uint16_t valor_raw);

/* Convierte un valor ADC de 12 bits a un valor de 0 a 255 */
uint8_t adc_a_brillo(uint16_t valor_raw);

#endif /* POTENCIOMETRO_H */